service: MyProject

frameworkVersion: "2.30.3"
configValidationMode: error

package:
  exclude:
    - package-lock.json
    - package.json

plugins:
  - serverless-esbuild
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function
  - serverless-export-env
  - serverless-manifest-plugin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  appSync:
    - ${file(./serverless-appsync.yaml)}
  manifest:
    postProcess: ./config/manifest-post-process.js
    disablePostDeployGeneration: true
    disableOutput: true
    silent: true

functions:
  createTodo:
    handler: functions/create-todo.handler
    environment:
      TODOS_TABLE: !Ref TodosTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt TodosTable.Arn

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: byUserId
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: todos-table

  Outputs:
    AwsRegion:
      Value: ${self:custom.region}
    TodosTable:
      Value: !Ref TodosTable
